---
-
  hosts: all
  gather_facts: true 
  become: yes
  tasks:
     - name: get Ip
       debug:
         msg: >
              Host IPs{{ ansible_default_ipv4.address }}
  tasks:
     - name: kubelet svc status
       ansible.builtin.service:
                  name: kubelet 
              
... 
