---
-
  hosts: all
  become: yes
  tasks:
    - name: kubelet svc status
      ansible.builtin.shell:
         cmd: service kubelet status 
      register: statvar
    - name: status of kubelet
      debug: 
        msg: service state is {{statvar.stdout_lines.Active}}
...   
      
   
